#!/bin/bash

git rm -r --cached .
git add .
git clean -fdX
mysql -uroot -ppassword -e 'drop schema `domjudge`'
mysql -uroot -ppassword -e 'drop user `domjudge`'
mysql -uroot -ppassword -e 'drop user `domjudge`@`localhost`'
