<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Fri Jan 10 14:26:36 EST 2014.

define('DOMJUDGE_VERSION', '4.0.0DEV');

define('BINDIR',      '/home/codejam/domjudge/domserver/bin');
define('ETCDIR',      '/home/codejam/domjudge/domserver/etc');
define('WWWDIR',      '/home/codejam/domjudge/domserver/www');
define('LIBDIR',      '/home/codejam/domjudge/domserver/lib');
define('LIBEXTDIR',   '/home/codejam/domjudge/domserver/lib/ext');
define('LIBWWWDIR',   '/home/codejam/domjudge/domserver/lib/www');
define('LIBSUBMITDIR','/home/codejam/domjudge/domserver/lib/submit');
define('LOGDIR',      '/home/codejam/domjudge/domserver/log');
define('RUNDIR',      '/home/codejam/domjudge/domserver/run');
define('TMPDIR',      '/home/codejam/domjudge/domserver/tmp');
define('SUBMITDIR',   '/home/codejam/domjudge/domserver/submissions');

define('SUBMIT_DEFAULT', 2);
define('ENABLE_CMDSUBMIT_SERVER', 0);
define('ENABLE_WEBSUBMIT_SERVER', 1);

set_include_path(get_include_path() . PATH_SEPARATOR . LIBEXTDIR);
