<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and judgehost-config.php

// Generated from 'judgehost-static.php.in' on Mon Jan 13 10:26:42 EST 2014.

define('DOMJUDGE_VERSION', '4.0.0DEV');

define('BINDIR',      '/home/rui/domjudge/bin');
define('ETCDIR',      '/home/rui/domjudge/etc');
define('LIBDIR',      '/home/rui/domjudge/lib');
define('LIBJUDGEDIR', '/home/rui/domjudge/lib/judge');
define('LOGDIR',      '/home/rui/domjudge/output/log');
define('RUNDIR',      '/home/rui/domjudge/output/run');
define('TMPDIR',      '/home/rui/domjudge/output/tmp');
define('JUDGEDIR',    '/home/rui/domjudge/output/judging');

define('RUNUSER',     'domjudge-run');
define('USE_CGROUPS', '0');
